---
name: build asl (x86)
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - codename: bullseye
          - codename: buster
    steps:
      - uses: actions/checkout@v2

      - name: Grab asl-dahdi artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-x86.yml
          workflow_conclusion: success
          branch: fixes
          name: asl-dahdi-${{ matrix.codename }}-x86_64
          repo: AI5A/asl-dahdi
          path: docker.ai5a/dahdi

      - name: Build the docker builder image
        run: |
          pushd docker.ai5a
          sed -i "s/FROM debian:.*/FROM debian:${{ matrix.codename }}/" Dockerfile
          docker build -t asl-builder .
          popd

      - name: Build the package
        run: |
          docker run --rm -v $(pwd):/asl asl-builder

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allstarlink-${{ matrix.codename }}-x86_64
          path: |
            *.deb
            *.build
            *.buildinfo
            *.changes
